# Generated by Django 2.1.7 on 2019-03-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(default='Enter a description...'),
        ),
    ]
