# Generated by Django 2.1.7 on 2019-03-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Stock_history',
        ),
    ]
