# Generated by Django 2.1.7 on 2019-03-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20190323_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_history',
            old_name='adj_close',
            new_name='_adj_close',
        ),
        migrations.RenameField(
            model_name='stock_history',
            old_name='close',
            new_name='_close',
        ),
        migrations.RenameField(
            model_name='stock_history',
            old_name='date',
            new_name='_date',
        ),
        migrations.RenameField(
            model_name='stock_history',
            old_name='high',
            new_name='_high',
        ),
        migrations.RenameField(
            model_name='stock_history',
            old_name='low',
            new_name='_low',
        ),
        migrations.RenameField(
            model_name='stock_history',
            old_name='name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='stock_history',
            old_name='open',
            new_name='_open',
        ),
        migrations.RenameField(
            model_name='stock_history',
            old_name='volume',
            new_name='_volume',
        ),
    ]
