# Generated by Django 2.1.7 on 2019-03-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20190323_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_history',
            name='_date',
            field=models.CharField(max_length=50),
        ),
    ]
