# Generated by Django 2.1.7 on 2019-03-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20190323_1331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock_history',
            unique_together={('_name', '_date')},
        ),
    ]
